name: Build app workflow

on:
  push:
    tags: 'v*'
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'keystore/notally_jks.jks'
          encodedString: ${{ secrets.NOTALLY_KEYSTORE }}
      - uses: actions/checkout@v2
      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: build Release AAB
        run: ./gradlew app:bundleRelease
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.KEY_PASS }}
          SIGNING_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASS }}
      - name: Build Universal APK
        uses: skywall/universal-apk-builder@v1.0.1
        with:
          aab_path: "app/release/app-release.aab"
          keystore_path: "keystore/notally_jks.jks"
          keystore_password: ${{secrets.KEY_STORE_PASS}}
          keystore_alias: ${{secrets.KEY_ALIAS}}
          keystore_alias_password: ${{secrets.KEY_PASS}}
      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
            appId: ${{secrets.FB_APP_ID}}
            serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
            groups: QA
            file: ${{env.UNIVERSAL_APK_PATH}}
